# Data Configuration
data:
  librispeech_path: "data/LibriSpeech/wav" 
  #  uclass_path: "data/UCLASS"
  sample_rate: 16000
  n_mels: 80
  n_fft: 1024
  hop_length: 200
  win_length: 800
  normalize_audio: true
  trim_silence: true
  min_silence_threshold: 20
  mel_fmin: 0
  mel_fmax: 8000
  power: 1.0
  max_mel_length: 800
  max_text_length: 150
  min_mel_length: 20
  max_duration: 10.0

model:
  d_model: 512
  n_heads: 8
  n_encoder_layers: 3
  n_decoder_layers: 6
  d_ff: 2048
  dropout: 0.1
  n_phonemes: 100
  prenet_dropout: 0.5
  prenet_hidden_dim: 256
  postnet_channels: 512
  postnet_kernel_size: 5
  postnet_dropout: 0.1
  postnet_layers: 5
  ref_enc_filters: [32, 32, 64, 64, 128, 128]
  ref_enc_kernel_size: 3
  ref_enc_stride: 2
  ref_enc_dropout: 0.1

training:
  batch_size: 8
  epochs: 500
  learning_rate: 0.001
  beta1: 0.9
  beta2: 0.98
  epsilon: 0.000000001
  grad_clip_thresh: 1.0
  warmup_steps: 4000
  weight_decay: 0.0001
  device: "cuda"
  num_workers: 4
  pin_memory: true
  prefetch_factor: 2
  checkpoint_interval: 5000
  keep_last_checkpoints: 5
  log_interval: 100
  eval_interval: 1000
  save_interval: 10000
  experiment_dir: "experiments"
  checkpoint_dir: "checkpoints"
  log_dir: "logs"
  sample_dir: "samples"

validation:
  batch_size: 8
  num_samples: 4
  max_generation_length: 1000

loss:
  mel_loss_weight: 1.0
  postnet_mel_loss_weight: 1.0
  stop_token_loss_weight: 0.5